// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4W2jZ5ywIgzH66BwSJN77yxq8xCJw2j4',
    appId: '1:461233843349:web:aa1353c058615b8b5c7f9c',
    messagingSenderId: '461233843349',
    projectId: 'kasir-ba6aa',
    authDomain: 'kasir-ba6aa.firebaseapp.com',
    storageBucket: 'kasir-ba6aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGE2uxO5QtvrkIBJCxdYhNgxlRj0X7enY',
    appId: '1:461233843349:android:7163afb84bfb97475c7f9c',
    messagingSenderId: '461233843349',
    projectId: 'kasir-ba6aa',
    storageBucket: 'kasir-ba6aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSjiEWkoWtISD3tvhUHWBnFMPrDu_AJ4w',
    appId: '1:461233843349:ios:00851e9cb7f1b2a15c7f9c',
    messagingSenderId: '461233843349',
    projectId: 'kasir-ba6aa',
    storageBucket: 'kasir-ba6aa.firebasestorage.app',
    iosClientId: '461233843349-oav5nlkoa4q54sqnaan7f758ns7l42l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttterAppCasier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSjiEWkoWtISD3tvhUHWBnFMPrDu_AJ4w',
    appId: '1:461233843349:ios:00851e9cb7f1b2a15c7f9c',
    messagingSenderId: '461233843349',
    projectId: 'kasir-ba6aa',
    storageBucket: 'kasir-ba6aa.firebasestorage.app',
    iosClientId: '461233843349-oav5nlkoa4q54sqnaan7f758ns7l42l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttterAppCasier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4W2jZ5ywIgzH66BwSJN77yxq8xCJw2j4',
    appId: '1:461233843349:web:a5f51359349e00945c7f9c',
    messagingSenderId: '461233843349',
    projectId: 'kasir-ba6aa',
    authDomain: 'kasir-ba6aa.firebaseapp.com',
    storageBucket: 'kasir-ba6aa.firebasestorage.app',
  );
}
